version: '3'
services:
  postgres:
    container_name: postgres
    hostname: 'postgres'
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ${POSTGRES_SETUP_PATH}:/docker-entrypoint-initdb.d
      - ${POSTGRES_SRC_PATH}:/root/src
    networks:
      - dev-net

  centos_python:
      container_name: centos_python
      hostname: 'centos_python'
      build: "./docker/centos_python"
      tty: true
      restart: always
      volumes:
          - ${PYTHON_SRC_PATH}:/root/src
      depends_on:
        - postgres
      networks:
          - dev-net

networks:
    dev-net:
        driver: bridge

